# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/sony/yoshino-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter lilac maple maple_dsds poplar poplar_canada poplar_dsds poplar_kddi,$(TARGET_DEVICE)),)

endif
